version: '3.9'

services:
  web:
    image: nginx:latest
    ports:
      - '8080:80'
    volumes:
      - ./:/var/www/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php-fpm
      - db
  php-fpm:
    build:
      args:
        user: aceplus
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: note-app
    volumes:
      - ./:/var/www/html
    links:
      - db
  db:
    image: mysql:8.0
    ports:
      - 3312:3306
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - mysqldb:/var/lib/mysql
volumes:
  mysqldb: